Repository Project-insert-name/root-website, pull requests merged in 2024-02, with the labels that each got.

#99 Fribyte deployment tools
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
Labels: enhancement

#138 Build workflow
  .github/dependabot.yml
  .github/workflows/build.yml
  package.json
  pnpm-lock.yaml
Labels: workflow

#150 Docs
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
  README.md
  Sider.md
Labels: documentation
